[package]
name = "spytrap-b"
version = "0.1.0"
authors = ["user"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.14"
#mozdevice = "0.4.0"
mozdevice = { path="vendor/mozdevice" }
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
shell-escape = "0.1.5"
structopt = "0.3.25"

[dev-dependencies]
maplit = "1.0.2"
