[package]
name = "spytrap-adb"
version = "0.1.0"
authors = ["user"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
log = "0.4.14"
mozdevice = "0.5.0"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.9"
shell-escape = "0.1.5"
stalkerware-indicators = "0.2"

[dev-dependencies]
maplit = "1.0.2"
